version: '3.8'
name: docker-phpmyadmin

services:
  db:
    image: mysql:latest
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - 80:80
volumes:
  mysql: